/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peluqueriacanina.igu;

import com.mycompany.peluqueriacanina.logica.Controladora;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Javi
 */
public class SeleccionCargaDatos extends javax.swing.JFrame {

    private JFrame ventanaAnterior;

    /**
     * Creates new form SeleccionCargaDatos
     */
    public SeleccionCargaDatos(JFrame ventanaAnterior) {
        this.ventanaAnterior = ventanaAnterior;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        pTitle = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lGeneral1 = new javax.swing.JLabel();
        lGeneral = new javax.swing.JLabel();
        pGeneral = new javax.swing.JPanel();
        pCuidador = new javax.swing.JPanel();
        btnCuidador = new javax.swing.JButton();
        pMascota = new javax.swing.JPanel();
        btnMascota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTitle.setText("Peluquería Canina");

        javax.swing.GroupLayout pTitleLayout = new javax.swing.GroupLayout(pTitle);
        pTitle.setLayout(pTitleLayout);
        pTitleLayout.setHorizontalGroup(
            pTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTitleLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(lTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTitleLayout.setVerticalGroup(
            pTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTitleLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lTitle)
                .addGap(18, 18, 18))
        );

        lGeneral1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lGeneral1.setText("Carga de datos");

        lGeneral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lGeneral.setText("Seleccione una de las opciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lGeneral1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(lGeneral)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lGeneral1)
                .addGap(18, 18, 18)
                .addComponent(lGeneral)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pGeneral.setLayout(new java.awt.GridLayout(1, 0));

        btnCuidador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCuidador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuidadorx100.png"))); // NOI18N
        btnCuidador.setText("Cuidador");
        btnCuidador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCuidador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuidadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCuidadorLayout = new javax.swing.GroupLayout(pCuidador);
        pCuidador.setLayout(pCuidadorLayout);
        pCuidadorLayout.setHorizontalGroup(
            pCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuidadorLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pCuidadorLayout.setVerticalGroup(
            pCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuidadorLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pGeneral.add(pCuidador);

        btnMascota.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dog-face-logo-free-vectorx100.jpg"))); // NOI18N
        btnMascota.setText("Mascota");
        btnMascota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMascota.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMascotaLayout = new javax.swing.GroupLayout(pMascota);
        pMascota.setLayout(pMascotaLayout);
        pMascotaLayout.setHorizontalGroup(
            pMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMascotaLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btnMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        pMascotaLayout.setVerticalGroup(
            pMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMascotaLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pGeneral.add(pMascota);

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addComponent(pTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void dispose() {
        if (ventanaAnterior != null) {
            ventanaAnterior.setVisible(true);
        }

        super.dispose();
    }

    private void btnCuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuidadorActionPerformed
        try {
            Controladora controladora = new Controladora();
            CargaCuidador cargarCuidador = new CargaCuidador(controladora, SeleccionCargaDatos.this);
            SeleccionCargaDatos.this.setVisible(false);
            cargarCuidador.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(pPrincipal, "No se puedo conectar con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCuidadorActionPerformed

    private void btnMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMascotaActionPerformed
        try {
            Controladora controladora = new Controladora();
            CargaMascota cargaMascota = new CargaMascota(controladora, SeleccionCargaDatos.this);
            SeleccionCargaDatos.this.setVisible(false);
            cargaMascota.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(pPrincipal, "No se puedo conectar con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnMascotaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuidador;
    private javax.swing.JButton btnMascota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lGeneral;
    private javax.swing.JLabel lGeneral1;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel pCuidador;
    private javax.swing.JPanel pGeneral;
    private javax.swing.JPanel pMascota;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pTitle;
    // End of variables declaration//GEN-END:variables
}
